// kms-client-vue/src/views/meal-type/MealTypeIndex.vue
<template>
    <div class="meal-type">
        <h1>MealTypes index</h1>
        <br />
        <p>
            <a href="#">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>MealTypeName</th>
                    <th>Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(mealType, index) in mealTypes" :key="index">
                    <td>{{ mealType.id }}</td>
                    <td>{{ mealType.mealTypeName }}</td>
                    <td>{{ mealType.price }}</td>
                    <td>
                        <a load="/meal-type-edit(${item.id})">Edit</a> |
                        <router-link :to="'/meal-types/' + mealType.id"
                            >Details</router-link
                        >
                        |
                        <a load="/meal-type-delete(${item.id})">Delete</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { IMealType } from "@/domain/IMealType";

@Options({
    components: {},
    props: {},
})
export default class MealTypeIndex extends Vue {
    mealTypes: IMealType[] = [];

    async mounted(): Promise<void> {
        const response = await this.axios.get(
            "https://localhost:5001/api/v1/MealTypes"
        );
        this.mealTypes = response.data;
    }
}
</script>

// react-kms-client/src/containers/meal-types/MealTypeIndex.tsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { IMealType } from "../../dto/IMealType";
import { BaseService } from "../../services/base-service";

const MealTypeIndex = () => {
    const [mealTypes, setMealTypes] = useState([] as IMealType[]);

    const loadData = async () => {
        let result = await BaseService.getAll<IMealType>('/mealtypes')
        console.log(result);
        if (result.ok && result.data) {
            setMealTypes(result.data);
        }
    }

    useEffect(() => {
        loadData();
    }, [])

    return (
        <>
            <h1>Meal Types page</h1>

            <p>
                <a href="/MealTypes/Create">Create new</a>
            </p>
            <table className="table">
                <thead>
                    <tr>
                        <th>
                            Meal Type
                        </th>
                        <th>
                            Price
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {mealTypes.map(mealType => (
                        <tr key={mealType.id}>
                            <td>
                                {mealType.mealTypeName}
                            </td>
                            <td>
                                {mealType.price}
                            </td>
                            <td>
                                <Link to={'/MealTypes/edit/' + mealType.id}>Edit</Link> | 
                                <Link to={'/MealTypes/' + mealType.id}> Details</Link> | 
                                <Link to={'/MealTypes/delete/' + mealType.id}> Delete</Link>
                            </td>
                        </tr>
                    ))}

                </tbody>
            </table>
        </>
    );
}

export default MealTypeIndex;
